apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: blue
spec:
  selector:
    matchLabels:
      app: blue
  replicas: 3
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
      - name: blue
        image: pavangunda66/mydjango
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - name: http-server
          containerPort: 8000
