---
kind: Service
apiVersion: v1
metadata:
#   annotations:
#  service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:eu-west-1:xxx:certificate/xxx
#  service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
  name: bluelb
  labels:
    app: bluelb
spec:
  ports:
  - port: 8080
    targetPort: 8000
  selector:
    app: blue
# - name: https
#   port: 443
#   targetPort: 8080
  type: LoadBalancer
